### ISSUE TITLE
Configure eslint

### ISSUE THREAD

**Issue by jvcjunior** [ifactory-solutions/inside-server#1]

**Comment by jourdanrodrigues** [comment]
Acho que pra configurar o ESLint é bom decidir primeiro um padrão de código. De acordo com o próprio ESLint, há três grandes opções:

- [Google](https://google.github.io/styleguide/jsguide.html)
- [AirBNB](https://github.com/airbnb/javascript)
- [StandardJS](https://github.com/standard/standard) (+1 voto meu)

Deixemos hoje pra votação e amanhã subo a configuração mais votada.

Também gostaria de colocar em pauto o uso de _semi-colon_ (ponto e vírgula), já que o compilador do JavaScript evoluiu o bastante para não precisar:

- Tira _semi-colon_ (+1 voto meu)
- Põe _semi-colon_;

**Comment by paulonotz0r** [comment]
I vote for AirBNB pattern, because we're already using in [inside-client ESLint config](https://github.com/ifactory-solutions/inside-client/issues/3).

**Comment by andrelas1** [comment]
Why don't we define our style guide? we could even look at these three options that @jourdanrodrigues mentioned and get what we believe is worth and write our own styleguide.
By the way, I do like the AirBNB pattern and that would be my vote.
About the semi-colon, I think that with semi-colons the code is somewhat more readable. So I vote to keep semi-colons.

**Comment by jvcjunior** [comment]
Since we already have kind of defined our style, we just need to check which rules we want and add or remove from the rules file. Simple as that. This way we are evolving our style code over time. 

About the semi colon, I also prefer the code with it.

**Comment by jourdanrodrigues** [comment]
@paulonotz0r and @jvcjunior Agreed. Didn't know a style guide was already defined.
@andrelas1 We would have to pass through a lot of talk to define our own style guide. I don't disagree at all, I'm with you on it, but speed might be relevant.
