### ISSUE TITLE
Create initial setup project

### ISSUE THREAD

**Issue by jvcjunior** [ifactory-solutions/inside-server#2]

**Comment by andrelas1** [comment]
Guys, what are your thoughts on:

- [Koa JS](http://koajs.com/)
- [Meteor JS](https://www.meteor.com/)
- [Sails JS](http://sailsjs.com/)

Any ideas about our backend?

**Comment by jvcjunior** [comment]
I'll take a look at those options. Thanks @andrelas1

**Comment by adrianobrito** [comment]
I think that's pertinent to bring the discussion about tools to slack. Some guys could have another options beyond those exposed above, actually.

**Comment by jvcjunior** [comment]
I believe that we have  reached a consensus about creating the project with koa. Don't you think @adrianobrito @jouderianjr @juliosampaio @andrelas1 ?
