### ISSUE TITLE
Create Issue template

### ISSUE THREAD

**Issue by jvcjunior** [ifactory-solutions/inside-server#24]

**Comment by BrianCortes** [comment]
Hi, @jvcjunior do you have any reference we could use for this ?

**Comment by jvcjunior** [comment]
Hey @BrianCortes yes I have. When you try to create a new isso on create-react-app, for example, there a template on the issue body as you can see here:
https://github.com/facebookincubator/create-react-app/issues/new

Let me know if you need more info, ok? Thanks for your help! ❤️

**Comment by BrianCortes** [comment]
@jvcjunior ok,  I going to do this !

**Comment by jvcjunior** [comment]
Sure! I'll ask @paulonotz0r to let you do this! Go ahead!

Thanks a lot!

**Comment by jvcjunior** [comment]
Hey @BrianCortes you can take a look at this guy also:
https://github.com/ifactory-solutions/awesome-react-app/pull/46/
