### ISSUE TITLE
Add docker with mongo

### ISSUE THREAD

**Issue by jvcjunior** [ifactory-solutions/inside-server#7]
Maybe do something like [https://github.com/entria/graphql-dataloader-boilerplate](https://github.com/entria/graphql-dataloader-boilerplate)

**Comment by jourdanrodrigues** [comment]
Wasn't it resolved by [d46d1b9](https://github.com/ifactory-solutions/inside-server/commit/d46d1b90c4714da31dc0bcf9725e862a68cc69d9#diff-4e5e90c6228fd48698d074241c2ba760)?
