### ISSUE TITLE
Configure automatic Changelog generation

### ISSUE THREAD

**Issue by paulonotz0r** [ifactory-solutions/inside-server#9]
Like were proposed on ifactory-solutions/inside-client#5, we could use [this tool](https://github.com/conventional-changelog/standard-version) to configure an automatic Changelog generation.

**Comment by jourdanrodrigues** [comment]
@paulonotz0r Cool.

![Just do it](http://sneakerhistory.com/wp-content/uploads/2015/01/Nike-Just-Do-It.jpeg)
